### ISSUE TITLE
Newest version ssl error

### ISSUE THREAD

**Issue by herkalurk** [linuxserver/docker-sabnzbd#135]
## Expected Behavior
Docker image starts without error

## Current Behavior
SSL error occurs and docker container can't start after newest docker image

## Steps to Reproduce
1. restart docker container
2. read logs
3.
4.

## Environment
**OS:** CentOS 7
**CPU architecture:** x86_64
**How docker service was installed:** docker-ce repo

## Docker logs
```
2022-06-07 08:47:42,854::INFO::[SABnzbd:1168] SABnzbd.py-3.6.0
2022-06-07 08:47:42,854::INFO::[SABnzbd:1178] Commit = b31fedd85790c21488cbebd9730bdc00b2bdb385
2022-06-07 08:47:42,854::INFO::[SABnzbd:1180] Full executable path = /app/sabnzbd/SABnzbd.py
2022-06-07 08:47:42,855::INFO::[SABnzbd:1181] Arguments = "/app/sabnzbd/SABnzbd.py" "--config-file" "/config" "--server" "::"
2022-06-07 08:47:42,855::INFO::[SABnzbd:1182] Python-version = 3.9.7 (default, Nov 24 2021, 21:15:59)
[GCC 10.3.1 20211027]
2022-06-07 08:47:42,855::INFO::[SABnzbd:1183] Dockerized = True
2022-06-07 08:47:42,855::INFO::[SABnzbd:1184] CPU architecture = x86_64
2022-06-07 08:47:42,863::INFO::[SABnzbd:1187] Platform = posix - Linux-3.10.0-1160.66.1.el7.x86_64-x86_64-with
2022-06-07 08:47:42,864::INFO::[SABnzbd:1193] Preferred encoding = UTF-8
2022-06-07 08:47:42,864::DEBUG::[SABnzbd:1212] JSON-module = ujson 5.3.0
2022-06-07 08:47:42,865::INFO::[SABnzbd:1215] SSL version = OpenSSL 1.1.1o  3 May 2022
2022-06-07 08:47:42,868::INFO::[SABnzbd:1224] Certifi version = 2020.12.05
2022-06-07 08:47:42,868::INFO::[SABnzbd:1225] Loaded additional certificates from /etc/ssl/certs/ca-certificates.crt
2022-06-07 08:47:42,896::DEBUG::[SABnzbd:1234] Available certificates = {'x509': 132, 'crl': 0, 'x509_ca': 132}
2022-06-07 08:47:42,897::DEBUG::[getipaddress:100] Local IPv4 address = 172.19.0.16
Traceback (most recent call last):
  File "/app/sabnzbd/SABnzbd.py", line 1786, in <module>
    main()
  File "/app/sabnzbd/SABnzbd.py", line 1238, in main
    publicipv4()
  File "/app/sabnzbd/sabnzbd/getipaddress.py", line 114, in publicipv4
    result = addresslookup4(sabnzbd.cfg.selftest_host())
  File "/app/sabnzbd/sabnzbd/getipaddress.py", line 48, in func_wrapper
    return sabnzbd.THREAD_POOL.submit(item, *args, **kwargs).result(max_timeout)
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 447, in result
    raise TimeoutError()
concurrent.futures._base.TimeoutError
2022-06-07 08:47:48,732::INFO::[SABnzbd:1167] --------------------------------
```

**Comment by aptalca** [comment]
Our ci tests as well as a local test all work fine: https://ci-tests.linuxserver.io/linuxserver/sabnzbd/latest/index.html
