### ISSUE TITLE
[BUG] downloads folder not mapping

### ISSUE THREAD

**Issue by BrandonG777** [linuxserver/docker-sabnzbd#233]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

downloads folder isn't being mapped

### Expected Behavior

download folder has mapped in 4.3.2-ls169

### Steps To Reproduce

just mapping a downloads folder

### Environment

```markdown
- OS: unRAID 6.12.10
- How docker service was installed: built-in
```

### CPU architecture

x86-64

### Docker creation

```bash
docker run
  -d
  --name='sabnzbd'
  --net='proxynet'
  --cpuset-cpus='6,8,7,9'
  -e TZ="America/Chicago"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="z"
  -e HOST_CONTAINERNAME="sabnzbd"
  -e 'DOCKER_MODS'='ghcr.io/themepark-dev/theme.park:sabnzbd'
  -e 'TP_DOMAIN'='themepark.bahama.site'
  -e 'TP_THEME'='dracula'
  -e 'PUID'='99'
  -e 'PGID'='100'
  -e 'UMASK'='022'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.webui='http://[IP]:[PORT:8080]'
  -l net.unraid.docker.icon='https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/sabnzbd-logo.png'
  -p ':8080/tcp'
  -v '/mnt/user/downloads/':'/storage/downloads':'rw'
  -v '/mnt/user/media/':'/media/':'rw'
  -v '/mnt/user/restricted/':'/restricted':'rw'
  -v '/mnt/cache/appdata/sabnzbd':'/config':'rw' 'lscr.io/linuxserver/sabnzbd'
5628c3633a3678ad773f0651fbbff0bfd527b15d2601f547d560c92ea0843a4f
```

### Container logs

```bash
[mod-init] Running Docker Modification Logic
[mod-init] Adding themepark-dev/theme.park:sabnzbd to container
[mod-init] Downloading themepark-dev/theme.park:sabnzbd from ghcr.io
[mod-init] Installing themepark-dev/theme.park:sabnzbd
[mod-init] themepark-dev/theme.park:sabnzbd applied to container
[migrations] started
[migrations] no migrations found
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support the app dev(s) visit:
SABnzbd: https://sabnzbd.org/donate

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    99
User GID:    100
───────────────────────────────────────
Linuxserver.io version: 4.3.2-ls170
Build-date: 2024-07-05T09:39:24+00:00
───────────────────────────────────────
    
----------------------------
|  SABnzbd theme.park Mod  |
----------------------------
Variables set:
'TP_DOMAIN'=themepark.bahama.site
'TP_COMMUNITY_THEME'=
'TP_SCHEME'=
'TP_THEME'=dracula

No scheme set, defaulting to https
---------------------------
|  Adding the stylesheet  |
---------------------------
Stylesheet set to dracula
[custom-init] No custom files found, skipping...
2024-07-05 09:40:01,627::INFO::[SABnzbd:1144] --------------------------------
2024-07-05 09:40:01,627::INFO::[SABnzbd:1145] SABnzbd.py-4.3.2
2024-07-05 09:40:01,627::INFO::[SABnzbd:1155] Commit = 8a42abd1e78b0c29081a4d717c5b457f7bb3a473
2024-07-05 09:40:01,627::INFO::[SABnzbd:1157] Full executable path = /app/sabnzbd/SABnzbd.py
2024-07-05 09:40:01,627::INFO::[SABnzbd:1158] Arguments = "/app/sabnzbd/SABnzbd.py" "--config-file" "/config" "--server" "::"
2024-07-05 09:40:01,627::INFO::[SABnzbd:1159] Python-version = 3.12.3 (main, Apr 18 2024, 07:52:31) [GCC 13.2.1 20240309]
2024-07-05 09:40:01,627::INFO::[SABnzbd:1160] Dockerized = True
2024-07-05 09:40:01,627::INFO::[SABnzbd:1161] CPU architecture = x86_64
2024-07-05 09:40:01,629::INFO::[SABnzbd:1164] Platform = posix - Linux-6.1.79-Unraid-x86_64-with
2024-07-05 09:40:01,629::INFO::[SABnzbd:1170] Preferred encoding = UTF-8
2024-07-05 09:40:01,629::INFO::[SABnzbd:1192] SSL version = OpenSSL 3.3.1 4 Jun 2024
2024-07-05 09:40:01,629::INFO::[SABnzbd:1201] Certifi version = 2024.02.02
2024-07-05 09:40:01,629::INFO::[SABnzbd:1202] Loaded additional certificates from /lsiopy/lib/python3.12/site-packages/certifi/cacert.pem
2024-07-05 09:40:01,630::INFO::[SABnzbd:1212] Using INI file /config/sabnzbd.ini
2024-07-05 09:40:01,630::INFO::[filesystem:747] Creating directories: /downloads/sabnzbd
2024-07-05 09:40:01,630::ERROR::[filesystem:769] Failed making (/downloads/sabnzbd)
Traceback (most recent call last):
  File "/app/sabnzbd/sabnzbd/filesystem.py", line 763, in create_all_dirs
    os.mkdir(path_part_combined)
PermissionError: [Errno 13] Permission denied: '/downloads'
2024-07-05 09:40:01,630::ERROR::[filesystem:416] Cannot create directory /downloads/sabnzbd
2024-07-05 09:40:01,631::INFO::[postproc:143] Loading postproc queue
2024-07-05 09:40:01,631::INFO::[scheduler:190] Scheduling RSS interval task every 60 min (delay=7)
2024-07-05 09:40:01,632::INFO::[scheduler:215] Setting schedule for midnight auto history-purge
2024-07-05 09:40:01,632::INFO::[scheduler:224] Setting schedule for midnight BPS reset
2024-07-05 09:40:01,632::INFO::[scheduler:233] Setting schedule for midnight server expiration check
2024-07-05 09:40:01,632::INFO::[scheduler:242] Setting schedule for server quota check
2024-07-05 09:40:01,632::INFO::[__init__:328] All processes started
2024-07-05 09:40:01,632::INFO::[SABnzbd:339] Template location for Glitter is /app/sabnzbd/interfaces/Glitter
2024-07-05 09:40:01,632::INFO::[SABnzbd:339] Template location for Config is /app/sabnzbd/interfaces/Config
2024-07-05 09:40:01,632::INFO::[misc:1243] [N/A] Running external command: ['/usr/bin/unrar']
2024-07-05 09:40:01,637::INFO::[misc:1243] [N/A] Running external command: ['/usr/bin/7zz']
2024-07-05 09:40:01,647::INFO::[misc:1243] [N/A] Running external command: ['/usr/local/bin/par2', '-V']
2024-07-05 09:40:01,654::INFO::[SABnzbd:424] SABCTools module (v8.2.0)... found!
2024-07-05 09:40:01,654::INFO::[SABnzbd:425] SABCTools module is using SIMD set: AVX2
2024-07-05 09:40:01,654::INFO::[SABnzbd:426] SABCTools module is linked to OpenSSL: True
2024-07-05 09:40:01,654::INFO::[SABnzbd:446] Cryptography module (v42.0.7)... found!
2024-07-05 09:40:01,654::INFO::[SABnzbd:452] par2 binary... found (/usr/local/bin/par2)
2024-07-05 09:40:01,655::INFO::[SABnzbd:459] UNRAR binary... found (/usr/bin/unrar)
2024-07-05 09:40:01,655::INFO::[SABnzbd:467] UNRAR binary version 7.00
2024-07-05 09:40:01,655::INFO::[SABnzbd:474] 7za binary... found (/usr/bin/7zz)
2024-07-05 09:40:01,655::INFO::[SABnzbd:476] 7za binary version 23.01
2024-07-05 09:40:01,655::INFO::[SABnzbd:482] nice binary... found (/bin/nice)
2024-07-05 09:40:01,655::INFO::[SABnzbd:486] ionice binary... found (/bin/ionice)
2024-07-05 09:40:01,655::INFO::[SABnzbd:1406] Starting web-interface on :::8080
2024-07-05 09:40:01,655::INFO::[_cplogging:213] [05/Jul/2024:09:40:01] ENGINE Bus STARTING
[ls.io-init] done.
/lsiopy/lib/python3.12/site-packages/cherrypy/process/servers.py:416: UserWarning: Unable to verify that the server is bound on 8080
  warnings.warn(msg)
2024-07-05 09:40:06,774::INFO::[_cplogging:213] [05/Jul/2024:09:40:06] ENGINE Serving on http://:::8080
2024-07-05 09:40:06,774::INFO::[_cplogging:213] [05/Jul/2024:09:40:06] ENGINE Bus STARTED
2024-07-05 09:40:06,774::INFO::[SABnzbd:1445] Starting SABnzbd.py-4.3.2
2024-07-05 09:40:06,774::INFO::[filesystem:747] Creating directories: /downloads/sabnzbd
2024-07-05 09:40:06,775::ERROR::[filesystem:769] Failed making (/downloads/sabnzbd)
Traceback (most recent call last):
  File "/app/sabnzbd/sabnzbd/filesystem.py", line 763, in create_all_dirs
    os.mkdir(path_part_combined)
PermissionError: [Errno 13] Permission denied: '/downloads'
2024-07-05 09:40:06,775::ERROR::[filesystem:416] Cannot create directory /downloads/sabnzbd
2024-07-05 09:40:06,776::INFO::[dirscanner:112] Dirscanner starting up
2024-07-05 09:40:06,777::INFO::[notifier:157] Sending notification: SABnzbd - SABnzbd 4.3.2 started (type=startup, job_cat=None)
2024-07-05 09:40:06,777::INFO::[zconfig:61] No bonjour/zeroconf support installed
2024-07-05 09:40:06,777::INFO::[ssdp:108] Serving SSDP on 172.18.0.21 as SABnzbd
2024-07-05 09:40:06,779::INFO::[filesystem:747] Creating directories: /downloads/sabnzbd
2024-07-05 09:40:06,779::ERROR::[filesystem:769] Failed making (/downloads/sabnzbd)
Traceback (most recent call last):
  File "/app/sabnzbd/sabnzbd/filesystem.py", line 763, in create_all_dirs
    os.mkdir(path_part_combined)
PermissionError: [Errno 13] Permission denied: '/downloads'
2024-07-05 09:40:06,779::ERROR::[filesystem:416] Cannot create directory /downloads/sabnzbd
2024-07-05 09:40:06,779::INFO::[notifier:157] Sending notification: Warning - /downloads/sabnzbd is not writable at all. This blocks downloads.
To prevent all helpful warnings, disable Special setting 'helpful_warnings'. (type=warning, job_cat=None)
2024-07-05 09:40:06,779::WARNING::[misc:95] /downloads/sabnzbd is not writable at all. This blocks downloads.
To prevent all helpful warnings, disable Special setting 'helpful_warnings'.
2024-07-05 09:40:06,779::INFO::[database:607] Scheduled history purge
2024-07-05 09:40:06,780::INFO::[database:277] Removing completed jobs older than 365 days from history
2024-07-05 09:40:16,632::INFO::[rss:459] Starting scheduled RSS read-out for "NZBGeek Cart"
2024-07-05 09:40:17,182::INFO::[rss:234] RSS Feed https://api.nzbgeek.info/rss?t=-2&limit=100&dl=1&del=1&r=ETBu93iT9bAny524M5geX0XJKO2l0QL2 was empty
2024-07-05 09:40:19,345::INFO::[filesystem:747] Creating directories: /downloads/sabnzbd
2024-07-05 09:40:19,345::ERROR::[filesystem:769] Failed making (/downloads/sabnzbd)
Traceback (most recent call last):
  File "/app/sabnzbd/sabnzbd/filesystem.py", line 763, in create_all_dirs
    os.mkdir(path_part_combined)
PermissionError: [Errno 13] Permission denied: '/downloads'
2024-07-05 09:40:19,345::ERROR::[filesystem:416] Cannot create directory /downloads/sabnzbd
2024-07-05 09:40:32,185::INFO::[rss:475] Finished scheduled RSS read-outs
2024-07-05 09:40:33,492::INFO::[filesystem:747] Creating directories: /downloads/sabnzbd
2024-07-05 09:40:33,493::ERROR::[filesystem:769] Failed making (/downloads/sabnzbd)
Traceback (most recent call last):
  File "/app/sabnzbd/sabnzbd/filesystem.py", line 763, in create_all_dirs
    os.mkdir(path_part_combined)
PermissionError: [Errno 13] Permission denied: '/downloads'
2024-07-05 09:40:33,493::ERROR::[filesystem:416] Cannot create directory /downloads/sabnzbd
```

**Comment by thespad** [comment]
You're not mapping a folder called downloads
```
  -v '/mnt/user/downloads/':'/storage/downloads':'rw'
  -v '/mnt/user/media/':'/media/':'rw'
  -v '/mnt/user/restricted/':'/restricted':'rw'
  -v '/mnt/cache/appdata/sabnzbd':'/config':'rw' 'lscr.io/linuxserver/sabnzbd'
```

**Comment by BrandonG777** [comment]
okay something odd is happening. I definitely map a /downloads folder... investigating...

**Comment by BrandonG777** [comment]
Mislabel in unRAID for my downloads folder, was listed as "/downloads folder" but this was just the unRAID label, should have checked the actual mapping as you did. Thank you, for the help and pardon my ignorance!
