### ISSUE TITLE
" SABnzbd was started with encoding ANSI_X3.4-1968, this should be UTF-8. Expect problems with Unicoded file and directory names in downloads."

### ISSUE THREAD

**Issue by bleurgleblaster** [linuxserver/docker-sabnzbd#49]
Skip to content
 
Search or jump to…

Pull requests
Issues
Marketplace
Explore
 @cmacnevin Sign out
21
64 42 linuxserver/docker-sabnzbd
 Code  Issues 2  Pull requests 1  Projects 0  Wiki  Insights
@cmacnevin

" SABnzbd was started with encoding ANSI_X3.4-1968"
   
 
 
 
I'm getting a lot of crashes, likely from unicode filenames. I've seen this error tackled on other OS systems, but can't find anything related to the linuxserver docker image. 

                "build_version": "Linuxserver.io version:- 103 Build-date:- February-23-2018-23:13:15-UTC",

No symlinks are in use.

This is from the logs:

Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/share/sabnzbdplus/sabnzbd/assembler.py", line 92, in run
    filepath = get_filepath(long_path(cfg.download_dir.get_path()), nzo, nzf.filename)
  File "/usr/share/sabnzbdplus/sabnzbd/decorators.py", line 36, in call_func
    return f(*args, **kw)
  File "/usr/share/sabnzbdplus/sabnzbd/misc.py", line 1091, in get_filepath
    if os.path.exists(fullPath):
  File "/usr/lib/python2.7/genericpath.py", line 26, in exists
    os.stat(path)
UnicodeEncodeError: 'ascii' codec can't encode character u'\x96' in position 98: ordinal not in range(128)

Any idea how to fix that?

Cheers

**Comment by j0nnymoe** [comment]
Pull the latest image and see if that fixed the issue.

**Comment by bleurgleblaster** [comment]
Updated. Now, I can't get past the SSL Signing issue :( Is there an easy way to disable SSL in the .ini or somewhere?

**Comment by bleurgleblaster** [comment]
OK, the update seems to have fixed it. Took a bunch of messing around, and somehow it lost my config, but rebuilding it was quick enough. Cheers.
