### ISSUE TITLE
HTTP 500 No such file or directory: '/usr/share/sabnzbdplus/interfaces/Glitter/templates/main.tmpl'

### ISSUE THREAD

**Issue by treyturner** [linuxserver/docker-sabnzbd#50]
After the container has been running for some time, requests for the web root begin returning HTTP 500 with the following error printed to screen. Removing and recreating the container temporarily resolves the issue until some time later it happens again.
```
500 Internal Server Error
The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/usr/share/sabnzbdplus/cherrypy/_cprequest.py", line 670, in respond
  File "/usr/share/sabnzbdplus/cherrypy/lib/encoding.py", line 220, in __call__
  File "/usr/share/sabnzbdplus/cherrypy/_cpdispatch.py", line 60, in __call__
  File "/usr/share/sabnzbdplus/sabnzbd/interface.py", line 127, in internal_wrap
  File "/usr/share/sabnzbdplus/sabnzbd/interface.py", line 425, in index
  File "/usr/lib/python2.7/dist-packages/Cheetah/Template.py", line 1259, in __init__
    self._compile(source, file, compilerSettings=compilerSettings)
  File "/usr/lib/python2.7/dist-packages/Cheetah/Template.py", line 1546, in _compile
    self._fileMtime = os.path.getmtime(file)
  File "/usr/lib/python2.7/genericpath.py", line 62, in getmtime
    return os.stat(filename).st_mtime
OSError: [Errno 2] No such file or directory: '/usr/share/sabnzbdplus/interfaces/Glitter/templates/main.tmpl'

Powered by CherryPy 8.1.2
```

Host OS: QNAP TVS-873, QTS v4.3.5.0760 with Container Station v1.93579
```
[~] # docker info
Containers: 5
 Running: 5
 Paused: 0
 Stopped: 0
Images: 5
Server Version: 17.09.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.2.8
Operating System: QTS 4.3.5 (20181114)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 29.36GiB
Name: tron
ID: OXRI:ZXM2:LZNK:U5OK:GUJL:RQBV:LMXN:QSQA:QAQD:6CS3:GQ6U:RK43
Docker Root Dir: /share/CACHEDEV1_DATA/Public/container-station-data/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 98
 Goroutines: 105
 System Time: 2018-11-23T12:49:38.606440053-06:00
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No kernel memory limit support
```

```
docker run \
--name sabnzbd \
--restart=always \
-d \
-v /share/CACHEDEV1_DATA/.qpkg/.sabnzbd/config:/config \
-v /share/CACHEDEV1_DATA/.qpkg/.sabnzbd/incomplete-downloads:/incomplete-downloads \
-v /share/CACHEDEV1_DATA/usenet:/downloads \
-e HOME=/config \
-e PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
-e PGID=0 \
-e PUID=0 \
-e TERM=xterm \
-e TZ=America/Chicago \
-p 8805:8080 \
linuxserver/sabnzbd:unstable
```

```

2018-11-23 12:40:59,011::INFO::[_cplogging:219] [23/Nov/2018:12:40:59] HTTP
Request Headers:
  CONNECTION: keep-alive
  COOKIE: snatched_view=list; soon_view=thumb; suggest_view=thumb; late_view=list; blu_ray_com_new_releases_view=thumb; imdb_movies_in_theaters_view=thumb; imdb_box_office_view=thumb; imdb_top_250_movies_view=thumb; medusa_user="2|1:0|10:1541896164|11:medusa_user|44:MzgxNTI1NDgyOWI5M2I5NjRiYzBmZGM0MWJmYTc5MGY=|116bae568d04e0999962a5e8c08b3dc851998c93d452fc27e81d6830e45002a6"; user="2|1:0|10:1542610905|4:user|44:M2Y2MDk1YWI2Zjg0NDU1YzkzZDI0ZjY0ZTY3NWRmNzI=|cb59daa5e4fdd1b35cc1ed17a45f36e89f87d2f0b9595d2c022103ea0b98affd"; JSESSIONID=60midyj28866; ACEGI_SECURITY_HASHED_REMEMBER_ME_COOKIE=dHJleS50dXJuZXI6MTU3NDQwMTM2NDIwMzo3ZDQ4YjA0NmM2MDIwMTUyZTdjYzEyYjZiNmMyZjRkMA==; player-747265792e7475726e6572=9; jwplayer.volume=99; UbooquitySession=cmVhZCM3Njg3OTk5NjE4MDAxMTY1OTE4; ComicSettings=folder#path#asc
  HOST: <redacted>:8805
  UPGRADE-INSECURE-REQUESTS: 1
  CACHE-CONTROL: max-age=0
  Remote-Addr: 192.168.1.1
  ACCEPT: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
  USER-AGENT: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36
  ACCEPT-LANGUAGE: en-US,en;q=0.9
  DNT: 1
  ACCEPT-ENCODING: gzip, deflate
2018-11-23 12:40:59,012::ERROR::[_cplogging:219] [23/Nov/2018:12:40:59] HTTP
Traceback (most recent call last):
  File "/usr/share/sabnzbdplus/cherrypy/_cprequest.py", line 670, in respond
  File "/usr/share/sabnzbdplus/cherrypy/lib/encoding.py", line 220, in __call__
  File "/usr/share/sabnzbdplus/cherrypy/_cpdispatch.py", line 60, in __call__
  File "/usr/share/sabnzbdplus/sabnzbd/interface.py", line 127, in internal_wrap
  File "/usr/share/sabnzbdplus/sabnzbd/interface.py", line 425, in index
  File "/usr/lib/python2.7/dist-packages/Cheetah/Template.py", line 1259, in __init__
    self._compile(source, file, compilerSettings=compilerSettings)
  File "/usr/lib/python2.7/dist-packages/Cheetah/Template.py", line 1546, in _compile
    self._fileMtime = os.path.getmtime(file)
  File "/usr/lib/python2.7/genericpath.py", line 62, in getmtime
    return os.stat(filename).st_mtime
OSError: [Errno 2] No such file or directory: '/usr/share/sabnzbdplus/interfaces/Glitter/templates/main.tmpl'
2018-11-23 12:40:59,066::INFO::[_cplogging:219] [23/Nov/2018:12:40:59] HTTP
Request Headers:
  PRAGMA: no-cache
  REFERER: http://<redacted>:8805/
  HOST: <redacted>:8805
  CONNECTION: keep-alive
  CACHE-CONTROL: no-cache
  Remote-Addr: 192.168.1.1
  ACCEPT: image/webp,image/apng,image/*,*/*;q=0.8
  USER-AGENT: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36
  COOKIE: snatched_view=list; soon_view=thumb; suggest_view=thumb; late_view=list; blu_ray_com_new_releases_view=thumb; imdb_movies_in_theaters_view=thumb; imdb_box_office_view=thumb; imdb_top_250_movies_view=thumb; medusa_user="2|1:0|10:1541896164|11:medusa_user|44:MzgxNTI1NDgyOWI5M2I5NjRiYzBmZGM0MWJmYTc5MGY=|116bae568d04e0999962a5e8c08b3dc851998c93d452fc27e81d6830e45002a6"; user="2|1:0|10:1542610905|4:user|44:M2Y2MDk1YWI2Zjg0NDU1YzkzZDI0ZjY0ZTY3NWRmNzI=|cb59daa5e4fdd1b35cc1ed17a45f36e89f87d2f0b9595d2c022103ea0b98affd"; JSESSIONID=60midyj28866; ACEGI_SECURITY_HASHED_REMEMBER_ME_COOKIE=dHJleS50dXJuZXI6MTU3NDQwMTM2NDIwMzo3ZDQ4YjA0NmM2MDIwMTUyZTdjYzEyYjZiNmMyZjRkMA==; player-747265792e7475726e6572=9; jwplayer.volume=99; UbooquitySession=cmVhZCM3Njg3OTk5NjE4MDAxMTY1OTE4; ComicSettings=folder#path#asc
  ACCEPT-LANGUAGE: en-US,en;q=0.9
  DNT: 1
  ACCEPT-ENCODING: gzip, deflate
2018-11-23 12:40:59,066::ERROR::[_cplogging:219] [23/Nov/2018:12:40:59] HTTP
Traceback (most recent call last):
  File "/usr/share/sabnzbdplus/cherrypy/_cprequest.py", line 670, in respond
  File "/usr/share/sabnzbdplus/cherrypy/lib/encoding.py", line 220, in __call__
  File "/usr/share/sabnzbdplus/cherrypy/_cpdispatch.py", line 60, in __call__
  File "/usr/share/sabnzbdplus/cherrypy/_cptools.py", line 182, in handle_func
TypeError: staticfile() got multiple values for keyword argument 'filename'
```

No symlinks as volume mounts

**Comment by treyturner** [comment]
It's a pain to manually recreate the container when this happens, is there any additional information I can provide in order to better diagnose the issue? I would have no idea why the same files within the container are repeatedly lost. Changing themes has no impact.

**Comment by aptalca** [comment]
No idea. Perhaps a question for the sab devs?

May or may not be related, we don't recommend running containers as root

Another shot in the dark, could the container be running out of space somewhere?

**Comment by treyturner** [comment]
Thanks for the ideas; here's the rest of the information I have. There are 5 other containers running various Java and Python apps (like `linuxserver/medusa` and `linuxserver/ubooquity`) that don't seem to be having any issues. There's 7.5tb free on the container data mount. I'm not totally sure about the intricacies of this fact, but UID/GID 0 on QNAP systems belongs to an `admin` user as opposed to `root`. I switched over to the official `sabnzbd/sabnzbd` image to test, and the problem seems to have disappeared so far, but I'll post back if it happens on that image too.

**Comment by aceniner** [comment]
Having the same issue. Any solutions yet?

**Comment by treyturner** [comment]
> Having the same issue. Any solutions yet?

Switch to the official `sabnzbd/sabnzbd` image. Haven't had any troubles since cutting over.

**Comment by thelamer** [comment]
This file lives inside the container's ephemeral filesystem, unless the app deletes it we do not mess with it with any of our init logic. I am closing this case.
